const assert=require('node:assert/strict');
const c=require('./teacher-test-runtime.cjs')();
c.appEl={innerHTML:''};
const student={assessments:{pre:{done:true,score:7,total:10}}};
c.currentStudent=()=>student;
c.state.currentAssessment='pre';
c.state.assessmentQuiz={qIndex:0,correct:7,answered:true,picked:0};
c.renderAssessment();
assert.doesNotMatch(c.appEl.innerHTML,/คะแนน 7|qopt right|qopt wrong/);
c.renderAssessmentResult();
assert.doesNotMatch(c.appEl.innerHTML,/7\/10|70%/);
assert.match(c.appEl.innerHTML,/เริ่มบทที่ 1/);
assert.equal(c.assessmentLabel(student,'pre'),'7/10');
c.changeView=v=>{c.state.view=v};
c.startAssessment('pre');assert.equal(c.state.view,'assessmentresult');
student.assessments={};c.state.assessmentQuiz.qIndex=3;
c.startAssessment('pre');assert.equal(c.state.assessmentQuiz.qIndex,3);
c.state.currentAssessment='post';student.assessments.post={done:true,score:7,total:10};
c.renderAssessmentResult();assert.match(c.appEl.innerHTML,/7\/10/);
console.log('PASS: pretest score and feedback hidden, teacher score retained, resume and completed-attempt guard, posttest result visible');
