const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create function auth.uid() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;
 create table students(id text primary key,data jsonb not null,updated_at bigint default 0);
 create table app_settings(id text primary key,data jsonb,updated_at bigint);
 create table app_curriculum(id text primary key,data jsonb,updated_at bigint);
 create table student_sessions(user_id uuid primary key,student_id text);
 create function verify_teacher_pin(p_pin text) returns boolean language sql as $$select case when p_pin='unset' then null else p_pin='teacher-test' end$$;
 create function owns_student(id text) returns boolean language sql as $$select true$$;
 create function test_mode_enabled() returns boolean language sql as $$select coalesce((select (data->>'enabled')::boolean from app_settings where id='test_mode'),false)$$;
 grant select,update on students to authenticated;`);
 await db.exec(fs.readFileSync('supabase-cabinet-wallet.sql','utf8'));
 await db.exec('alter table cabinet_wallets drop constraint cabinet_wallets_student_id_fkey');
 await db.exec(fs.readFileSync('supabase-teacher-admin.sql','utf8'));
 const call=async(operations,pin='teacher-test')=>(await db.query('select teacher_manage($1,$2,$3) result',[pin,operations?'batch':'load',{operations}])).rows[0].result;
 const fresh=(code)=>({code,num:'1',lp:[{quizDone:true,postScore:4,postTotal:5},{quizDone:true,postScore:5,postTotal:5}],pStars:[1,0,1],badgeIds:['badge1'],score:2,unlockedLevel:1,assessments:{pre:{done:true,score:3,total:10}}});
 const a=fresh('alice');
 await assert.rejects(call([],''),/Invalid teacher PIN/);await assert.rejects(call([],'unset'),/Invalid teacher PIN/);
 let data=await call([{kind:'create',id:'roster_alice',data:a}]);assert(data.students.roster_alice);assert.equal(data.roster.length,1);
 await assert.rejects(call([{kind:'create',id:'roster_alice',data:a}]),/already exists/);
 await db.exec("insert into student_sessions values('00000000-0000-0000-0000-000000000001','roster_alice')");
 let before=data.students.roster_alice;
 data=await call([{kind:'edit',id:'roster_alice',expected:before._updatedAt,data:{...before,code:'alice2'},wallet:{prizes:['Sky Blue'],bonus_tickets:3}}]);
 assert(!data.students.roster_alice);assert(data.students.roster_alice2);assert.deepEqual(data.wallets.roster_alice2.prizes,['Sky Blue']);
 assert.equal((await db.query('select student_id from student_sessions')).rows[0].student_id,'roster_alice2');
 await assert.rejects(call([{kind:'edit',id:'roster_alice2',expected:0,data:{...a,code:'alice2'}}]),/CONFLICT/);
 const old=data.students.roster_alice2;
 data=await call([{kind:'reset',id:'roster_alice2',data:{...old,lp:[],pStars:[],badgeIds:[],score:0,unlockedLevel:0},wallet:{prizes:[],bonus_tickets:0}}]);
 assert.equal(data.students.roster_alice2._rankStars,0);assert.equal(data.wallets.roster_alice2.prizes.length,0);
 await db.exec('set role authenticated');
 await assert.rejects(db.query('update students set data=$1 where id=$2',[old,'roster_alice2']),/ADMIN_CHANGED/);
 await db.exec('reset role');
 await assert.rejects(call([{kind:'create',id:'roster_bob',data:fresh('bob')},{kind:'create',id:'roster_bad',data:fresh('!')}]),/Invalid student code/);
 assert(!(await call()).students.roster_bob,'failed batch must roll back all changes');
 await call([{kind:'create',id:'roster_bob',data:fresh('bob')}]);
 let c=JSON.parse(JSON.stringify(require('./teacher-test-runtime.cjs')().teacherAdminTest.defaults));c.previous=JSON.parse(JSON.stringify(c));c.baseUpdatedAt=0;c.lessons.splice(0,1);c.videos.splice(0,1);c.modules.prompts.reverse();
 const save=async(c,pin='teacher-test')=>db.query('select teacher_save_curriculum($1,$2)',[pin,c]);
 await assert.rejects(save(c,'unset'),/Invalid teacher PIN/);
 await save(c);
 data=await call();assert.equal(data.students.roster_bob.lp.length,4);assert.equal(data.students.roster_bob.lp[0].postScore,5);
 assert.deepEqual(data.students.roster_bob.pStars,[1,0,1]);
 await assert.rejects(save(c),/CONFLICT/);
 const wallet=(await db.query("select cabinet_account('roster_bob',null) w")).rows[0].w;assert.equal(wallet.tickets,1);
 await call([{kind:'wallet',id:'roster_bob',wallet:{prizes:[],bonus_tickets:2}}]);
 assert.equal((await db.query("select cabinet_account('roster_bob',null) w")).rows[0].w.tickets,3);
 await call([{kind:'delete',id:'roster_alice2'}]);data=await call();assert(!data.students.roster_alice2);assert(!data.wallets.roster_alice2);
 assert.equal((await db.query('select count(*) n from student_sessions')).rows[0].n,0);
 await db.exec(`insert into app_settings values('test_mode','{"enabled":true}',0)`);
 await assert.rejects(call([{kind:'delete',id:'roster_bob'}]),/another classroom/);
 assert.equal(Object.keys((await call()).students).length,0);
 const priv=(await db.query("select has_function_privilege('anon','teacher_manage(text,text,jsonb)','EXECUTE') a,has_table_privilege('authenticated','teacher_audit','SELECT') b,has_function_privilege('anon','teacher_save_curriculum(text,jsonb)','EXECUTE') c")).rows[0];assert.deepEqual(priv,{a:false,b:false,c:false});
 await db.close();console.log('PASS: teacher authentication, create/edit/rename/cascade, duplicate/conflict, scoped reset, stale writes, atomic rollback, content remap, wallet tickets, delete, mode isolation, permissions');
})().catch(e=>{console.error(e);process.exit(1);});
